// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ExtractPKG(arg1, arg2) {
  return window['go']['main']['App']['ExtractPKG'](arg1, arg2);
}

export function GetImgBase64(arg1) {
  return window['go']['main']['App']['GetImgBase64'](arg1);
}

export function GetRepkgVersion() {
  return window['go']['main']['App']['GetRepkgVersion']();
}

export function GetWallpaperProjectInfo(arg1) {
  return window['go']['main']['App']['GetWallpaperProjectInfo'](arg1);
}

export function GetWallpapers() {
  return window['go']['main']['App']['GetWallpapers']();
}

export function OpenDirInExploer(arg1) {
  return window['go']['main']['App']['OpenDirInExploer'](arg1);
}

export function SelectBaseDir() {
  return window['go']['main']['App']['SelectBaseDir']();
}
