// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ExtractPKG(arg1:string,arg2:string):Promise<void>;

export function GetImgBase64(arg1:string):Promise<string>;

export function GetRepkgVersion():Promise<void>;

export function GetWallpaperProjectInfo(arg1:string):Promise<string>;

export function GetWallpapers():Promise<string>;

export function OpenDirInExploer(arg1:string):Promise<void>;
